export enum PermissionType {
  FULL_ACCESS = "FULL_ACCESS",
  ATRIBUIR_PROVA = "ATRIBUIR_PROVA",
  LANCAMENTO_NOTAS_AVALIACOES = "LANCAMENTO_NOTAS_AVALIACOES",
  TESTE = "TESTE",
  ESTATISTICA_CANDIDATOS_INSCRITOS = "ESTATISTICA_CANDIDATOS_INSCRITOS",
  ESTATISTICA_CANDIDATOS_POR_DIA = "ESTATISTICA_CANDIDATOS_POR_DIA",
  MOVIMENTAR_ESTUDANTES_POR_HORARIO = "MOVIMENTAR_ESTUDANTES_POR_HORARIO",
  LISTA_ESTUDANTES_ESPECIAIS = "LISTA_ESTUDANTES_ESPECIAIS",
  LISTAR_COMUNICACAO_INTERNA = "LISTAR_COMUNICACAO_INTERNA",
  EMITIR_COMUNICACAO_INTERNA = "EMITIR_COMUNICACAO_INTERNA",
  LISTAR_HORARIOS_ELIMINADOS = "LISTAR_HORARIOS_ELIMINADOS",
  ATRIBUICAO_DE_TURMA_POR_ESTUDANTE = "ATRIBUICAO_DE_TURMA_POR_ESTUDANTE",
  INSCRICAO_EXAME_ACESSO_ESPECIAL = "INSCRICAO_EXAME_ACESSO_ESPECIAL",
  RESETAR_PROVA_CANDIDATO = "RESETAR_PROVA_CANDIDATO",
  MAPA_ANUAL_ESTUDANTES_FINALISTAS = "MAPA_ANUAL_ESTUDANTES_FINALISTAS",
  ACESSOS_POR_UTILIZADOR = "ACESSOS_POR_UTILIZADOR",
  LISTA_DOCENTES_REGENTES = "LISTA_DOCENTES_REGENTES",
  FAZER_INSCRICAO_GRADE_CURRICULAR = "FAZER_INSCRICAO_GRADE_CURRICULAR",
  ACESSOS_FUNCIONALIDADES_POR_GRUPO = "ACESSOS_FUNCIONALIDADES_POR_GRUPO",
  PAUTA_GERAL_EXAME_ACESSO = "PAUTA_GERAL_EXAME_ACESSO",
  ADMITIR_CANDIDATO = "ADMITIR_CANDIDATO",
  ACTUALIZAR_SENHA_DOCENTE = "ACTUALIZAR_SENHA_DOCENTE",
  VISUALIZAR_HORARIO_POR_DOCENTE = "VISUALIZAR_HORARIO_POR_DOCENTE",
  LISTAR_SOLICITACOES = "LISTAR_SOLICITACOES",
  LISTA_INSCRICOES_POR_HORARIOS = "LISTA_INSCRICOES_POR_HORARIOS",
  VISUALIZAR_HORARIO_POR_SALA = "VISUALIZAR_HORARIO_POR_SALA",
  REGISTRO_PRIMARIO_MATRICULADOS = "REGISTRO_PRIMARIO_MATRICULADOS",
  TALA_EM_DESUSO = "TALA_EM_DESUSO",
  MIGRACAO_DADOS_AREA_FINANCEIRA_POS_GRADUACAO = "MIGRACAO_DADOS_AREA_FINANCEIRA_POS_GRADUACAO",
  DEFINIR_ESPECIALIDADE_POS_GRADUACAO = "DEFINIR_ESPECIALIDADE_POS_GRADUACAO",
  CONTROLE_LANCAMENTOS_SUMARIOS = "CONTROLE_LANCAMENTOS_SUMARIOS",
  MARCACAO_ASSIDUIDADES_AULAS_CAMPO = "MARCACAO_ASSIDUIDADES_AULAS_CAMPO",
  LISTA_CANDIDATOS_ADMITIDOS = "LISTA_CANDIDATOS_ADMITIDOS",
  ESTATISTICA_NOTAS_LANCADAS = "ESTATISTICA_NOTAS_LANCADAS",
  HORARIOS_COM_CONFLITOS = "HORARIOS_COM_CONFLITOS",
  LISTA_DOCENTES_AFETADOS = "LISTA_DOCENTES_AFETADOS",
  REGISTRO_PRIMARIO_BD_POS_GRADUACAO = "REGISTRO_PRIMARIO_BD_POS_GRADUACAO",
  DEFESA = "DEFESA",
  PAGAMENTO_TFC = "PAGAMENTO_TFC",
  ACTIVIDADES_LECTIVAS = "ACTIVIDADES_LECTIVAS",
  HISTORICO_ATUALIZACAO_SALDO = "HISTORICO_ATUALIZACAO_SALDO",
  PERMISSAO_LANC_NOTA_FORA_PRAZO = "PERMISSAO_LANC_NOTA_FORA_PRAZO",
  MARCAR_DEFESA = "MARCAR_DEFESA",
  LISTAR_VIGILANTES_POR_PROVA = "LISTAR_VIGILANTES_POR_PROVA",
  DEFINIR_DIRECTOR_CURSO = "DEFINIR_DIRECTOR_CURSO",
  LISTAR_AFETACOES_POR_UC = "LISTAR_AFETACOES_POR_UC",
  CONTROLE_ATUALIZACAO_SALDO = "CONTROLE_ATUALIZACAO_SALDO",
  HORAS_DE_VIGILANCIA = "HORAS_DE_VIGILANCIA",
  MARCAR_ASSIDUIDADE_PROVA = "MARCAR_ASSIDUIDADE_PROVA",
  LISTAR_ESTUDANTES_POR_ESTADO_MATRICULA = "LISTAR_ESTUDANTES_POR_ESTADO_MATRICULA",
  LISTAR_ESTUDANTES_FINALISTAS = "LISTAR_ESTUDANTES_FINALISTAS",
  PERMISSAO_PARA_EDITAR_HORARIO = "PERMISSAO_PARA_EDITAR_HORARIO",
  ISENCAO_PAGAMENTOS = "ISENCAO_PAGAMENTOS",
  ESTUDANTES_INSCRITOS_POR_AVALIACAO = "ESTUDANTES_INSCRITOS_POR_AVALIACAO",
  ACTIVAR_MATRICULA_CANCELADA = "ACTIVAR_MATRICULA_CANCELADA",
  PRAZOS_PARA_CRIACAO_HORARIOS = "PRAZOS_PARA_CRIACAO_HORARIOS",
  ACTIVIDADES_LECTIVAS_MPGS = "ACTIVIDADES_LECTIVAS_MPGS",
  CALENDARIO_PROVAS = "CALENDARIO_PROVAS",
  PRAZO_MARCACAO_PROVAS_LANC_NOTAS = "PRAZO_MARCACAO_PROVAS_LANC_NOTAS",
  PRAZO_CRIACAO_HORARIOS_MPGS = "PRAZO_CRIACAO_HORARIOS_MPGS",
  LISTAR_HORARIOS_SEM_COM_SALA = "LISTAR_HORARIOS_SEM_COM_SALA",
  LISTA_ESTUDANTES_POR_NACIONALIDADE = "LISTA_ESTUDANTES_POR_NACIONALIDADE",
  IMAGEM_ABERTURA_PORTAL_ESTUDANTE = "IMAGEM_ABERTURA_PORTAL_ESTUDANTE",
  PARAMETROS_GERAIS_AVALIACAO = "PARAMETROS_GERAIS_AVALIACAO",
  LISTAGEM_GERAL_ESTUDANTES = "LISTAGEM_GERAL_ESTUDANTES",
  ESTUDANTES_DEVEDORES = "ESTUDANTES_DEVEDORES",
  PAUTA_GERAL_POR_UC = "PAUTA_GERAL_POR_UC",
  ESTUDANTES_INATIVOS_AC = "ESTUDANTES_INATIVOS_AC",
  DIAS_MARCADOS_ISENTOS = "DIAS_MARCADOS_ISENTOS",
  HISTORICO_ATUALIZACAO_SALDO_MAF = "HISTORICO_ATUALIZACAO_SALDO_MAF",
  LISTAR_ESTUDANTES_COM_ISENCAO_PROPINA = "LISTAR_ESTUDANTES_COM_ISENCAO_PROPINA",
  LANCAMENTO_PROGRAMA_UC = "LANCAMENTO_PROGRAMA_UC",
  ORIENTANDOS_POR_DOCENTE = "ORIENTANDOS_POR_DOCENTE",
  LISTAR_ESTADO_MATRICULA_ESTUDANTE_POR_HORARIO = "LISTAR_ESTADO_MATRICULA_ESTUDANTE_POR_HORARIO",
  HISTORICO_BOLSAS = "HISTORICO_BOLSAS",
  LISTA_ESTUDANTES_INATIVOS = "LISTA_ESTUDANTES_INATIVOS",
  MEUS_ORIENTANDOS = "MEUS_ORIENTANDOS",
  ORIENTADORES = "ORIENTADORES",
  PARAMETROS_TFC = "PARAMETROS_TFC",
  LISTA_ESTUDANTES_FINALISTAS_INACTIVOS = "LISTA_ESTUDANTES_FINALISTAS_INACTIVOS",
  DISCIPLINAS_SEM_SIGLA = "DISCIPLINAS_SEM_SIGLA",
  LISTA_ESTUDANTES_PERSONALIZADA = "LISTA_ESTUDANTES_PERSONALIZADA",
  VALIDACAO_PROGRAMA_UC = "VALIDACAO_PROGRAMA_UC",
  PARAMETROS_ANO_LECTIVO = "PARAMETROS_ANO_LECTIVO",
  LISTAR_DOCENTES_SUBSTITUTO = "LISTAR_DOCENTES_SUBSTITUTO",
  HISTORICO_LANCAMENTO_NOTAS = "HISTORICO_LANCAMENTO_NOTAS",
  FUNCIONALIDADES_POR_UTILIZADOR = "FUNCIONALIDADES_POR_UTILIZADOR",
  CONTROLE_GERAL_SUMARIOS_ASSIDUIDADE = "CONTROLE_GERAL_SUMARIOS_ASSIDUIDADE",
  ADMITIR_CANDIDATURA_UNIVERSIDADE_PUBLICA = "ADMITIR_CANDIDATURA_UNIVERSIDADE_PUBLICA",
  ALTERAR_PROVA = "ALTERAR_PROVA",
  LANCAMENTO_NOTAS_MPGS = "LANCAMENTO_NOTAS_MPGS",
  LANCAR_NOTA_CANDIDATURA_ARQUITETURA = "LANCAR_NOTA_CANDIDATURA_ARQUITETURA",
  LISTA_ESTUDANTES_MATRICULADOS = "LISTA_ESTUDANTES_MATRICULADOS",
  SUMARIOS_POR_LANCAR_LAST52 = "SUMARIOS_POR_LANCAR_LAST52",
  ANULAR_DIPLOMA_ESTUDANTE = "ANULAR_DIPLOMA_ESTUDANTE",
  LISTA_ESTUDANTES_DIVERSOS_POS_GRAD = "LISTA_ESTUDANTES_DIVERSOS_POS_GRAD",
  LANCAMENTO_PAUTA = "LANCAMENTO_PAUTA",
  VALIDACAO_PAUTA_DOCENTE = "VALIDACAO_PAUTA_DOCENTE",
  ALTERAR_ESTADO_PAGAMENTO = "ALTERAR_ESTADO_PAGAMENTO",
  LISTAR_LOGS_ACESSO = "LISTAR_LOGS_ACESSO",
  LISTAGEM_ESTUDANTES_PROPINAS = "LISTAGEM_ESTUDANTES_PROPINAS",
  LISTAR_MENSALIDADES_POR_CURSO = "LISTAR_MENSALIDADES_POR_CURSO",
  LISTA_DOCENTE_CONTRATO = "LISTA_DOCENTE_CONTRATO",
  UTILIZADORES_LOGADOS_CHAT = "UTILIZADORES_LOGADOS_CHAT",
  CARGOS_REITORIA_ADMINISTRATIVO = "CARGOS_REITORIA_ADMINISTRATIVO",
  ESTATISTICA_ESTUDANTES_APROVADOS_REPROVADOS = "ESTATISTICA_ESTUDANTES_APROVADOS_REPROVADOS",
  LISTA_CANDIDATOS_SEM_PROVAS_MARCADAS = "LISTA_CANDIDATOS_SEM_PROVAS_MARCADAS",
  LISTAR_HORARIO_PROVA_POR_CURSO = "LISTAR_HORARIO_PROVA_POR_CURSO",
  GESTAO_UNIDADE_CURRICULAR_DEPARTAMENTO = "GESTAO_UNIDADE_CURRICULAR_DEPARTAMENTO",
  LISTA_CANDIDATOS_ADMITIDOS_SEM_MATRICULAS = "LISTA_CANDIDATOS_ADMITIDOS_SEM_MATRICULAS",
  BLOQUEAR_ACESSOS = "BLOQUEAR_ACESSOS",
  CONTROLE_GERAL_ASSIDUIDADE_POR_DOCENTE = "CONTROLE_GERAL_ASSIDUIDADE_POR_DOCENTE",
  MINHAS_ASSIDUIDADES = "MINHAS_ASSIDUIDADES",
  MODULOS = "MODULOS",
  ACESSOS_TODOS = "ACESSOS_TODOS",
  PAGINAS = "PAGINAS",
  CRIAR_HORARIO_POR_TURMA1 = "CRIAR_HORARIO_POR_TURMA1",
  LISTAR_HORARIOS = "LISTAR_HORARIOS",
  CRIAR_HORARIO = "CRIAR_HORARIO",
  CRIAR_TURMA = "CRIAR_TURMA",
  LISTAR_UTILIZADORES_LOGADOS = "LISTAR_UTILIZADORES_LOGADOS",
  UTILIZADORES = "UTILIZADORES",
  GRUPOS = "GRUPOS",
  ATRIBUICAO_BOLSA_DESCONTO = "ATRIBUICAO_BOLSA_DESCONTO",
  VISUALIZAR_HORARIO_POR_UC = "VISUALIZAR_HORARIO_POR_UC",
  HORARIO_AULAS_SEMANAL = "HORARIO_AULAS_SEMANAL",
  LISTAR_SOLICITACOES_MC = "LISTAR_SOLICITACOES_MC",
  SOLICITACOES_ENCAMINHADAS = "SOLICITACOES_ENCAMINHADAS",
  SOLICITACOES_ENCAMINHADAS2 = "SOLICITACOES_ENCAMINHADAS2",
  INSTITUICOES = "INSTITUICOES",
  ISENCAO_PAGAMENTOS_MGBD = "ISENCAO_PAGAMENTOS_MGBD",
  LISTAR_BOLSEIROS = "LISTAR_BOLSEIROS",
  ISENCAO_PAGAMENTOS_MGBD_LS = "ISENCAO_PAGAMENTOS_MGBD_LS",
  PAGAMENTOS_BOLSEIROS = "PAGAMENTOS_BOLSEIROS",
  PERCENTAGEM_APROVEITAMENTO = "PERCENTAGEM_APROVEITAMENTO",
  AVISOS = "AVISOS",
  MARCAR_ASSIDUIDADE_MSA = "MARCAR_ASSIDUIDADE_MSA",
  LISTAR_CANDIDATURAS_DOCENTE = "LISTAR_CANDIDATURAS_DOCENTE",
  CALENDARIO_PROVAS_MCAL = "CALENDARIO_PROVAS_MCAL",
  LISTA_PRESENCA = "LISTA_PRESENCA",
  CANDIDATOS_INSCRITOS = "CANDIDATOS_INSCRITOS",
  ESTATISTICA_MGBD = "ESTATISTICA_MGBD",
  DEFINIR_PRAZOS_ESTADOS_MATRICULA = "DEFINIR_PRAZOS_ESTADOS_MATRICULA",
  PRAZO_MARCACAO_PROVAS_LANC_NOTAS2 = "PRAZO_MARCACAO_PROVAS_LANC_NOTAS2",
  DEFINIR_VAGAS_POR_CURSO = "DEFINIR_VAGAS_POR_CURSO",
  DEFINIR_VAGAS_POR_CURSO2 = "DEFINIR_VAGAS_POR_CURSO2",
  ESTUDANTES_COM_PROPINAS_PAGA = "ESTUDANTES_COM_PROPINAS_PAGA",
  ESTUDANTES_MATRICULADOS_MPGS = "ESTUDANTES_MATRICULADOS_MPGS",
  DIAS_ISENTOS = "DIAS_ISENTOS",
  LANCAMENTO_NOTAS_MPGS2 = "LANCAMENTO_NOTAS_MPGS2",
  ACTUALIZACAO_DADOS_DOCENTE = "ACTUALIZACAO_DADOS_DOCENTE",
  LISTAR_FACULDADES = "LISTAR_FACULDADES",
  ESTUDANTES_POR_UC = "ESTUDANTES_POR_UC",
  VISUALIZAR_ASSIDUIDADES = "VISUALIZAR_ASSIDUIDADES",
  PARAMETROS_MGH = "PARAMETROS_MGH",
  API_TESTES = "API_TESTES",
  CALENDARIO_AULAS = "CALENDARIO_AULAS",
  LISTAR_INSCRITOS_UC = "LISTAR_INSCRITOS_UC",
  LISTAR_ESTUDANTES_MATRICULADOS2 = "LISTAR_ESTUDANTES_MATRICULADOS2",
  SUMARIOS_LANCADOS = "SUMARIOS_LANCADOS",
  GESTAO_AFETACOES = "GESTAO_AFETACOES",
  TRABALHO_FIM_CURSO = "TRABALHO_FIM_CURSO",
  SUMARIO_POR_VALIDAR = "SUMARIO_POR_VALIDAR",
  PARAMETROS_MGD = "PARAMETROS_MGD",
  LISTAR_ESTUDANTES_SEM_INSCRICOES_CURSO = "LISTAR_ESTUDANTES_SEM_INSCRICOES_CURSO",
  LISTAR_ESTUDANTES_SEM_INSCRICAO_UC = "LISTAR_ESTUDANTES_SEM_INSCRICAO_UC",
  VALIDACAO_DOCENTE = "VALIDACAO_DOCENTE",
  PARAMETROS_MSA = "PARAMETROS_MSA",
}

export const PermissionTypeDetails = {
  FULL_ACCESS: { designacao: 'Todos os acesso', sigla: 'full.access' },
  ATRIBUIR_PROVA: { designacao: "Atribuir Prova", sigla: "mgea_atp" },
  LANCAMENTO_NOTAS_AVALIACOES: { designacao: "Lançamento de Notas de Avaliações", sigla: "mga_a_lan" },
  TESTE: { designacao: "teste", sigla: "d" },
  ESTATISTICA_CANDIDATOS_INSCRITOS: { designacao: "Estatistica De Candidatos Inscritos", sigla: "mgea_e" },
  ESTATISTICA_CANDIDATOS_POR_DIA: { designacao: "Estatistica De Candidatos Inscritos Por Dia", sigla: "mgea_ed" },
  MOVIMENTAR_ESTUDANTES_POR_HORARIO: { designacao: "Movimentar Estudantes Por Horário", sigla: "mgim_a_meph" },
  LISTA_ESTUDANTES_ESPECIAIS: { designacao: "Lista De Estudantes Especiais", sigla: "mgea_les" },
  LISTAR_COMUNICACAO_INTERNA: { designacao: "Listar Comunicação Interna", sigla: "mgdm_lci" },
  EMITIR_COMUNICACAO_INTERNA: { designacao: "Emitir Comunicação Interna", sigla: "mgdm_a_eci" },
  LISTAR_HORARIOS_ELIMINADOS: { designacao: "Listar Horários Eliminados", sigla: "mgh_lhe" },
  ATRIBUICAO_DE_TURMA_POR_ESTUDANTE: { designacao: "Atribuição De Turma por Estudante", sigla: "mgc_at" },
  INSCRICAO_EXAME_ACESSO_ESPECIAL: { designacao: "Inscrição Para o Exame De Acesso Epoca Especial", sigla: "mgea_in" },
  RESETAR_PROVA_CANDIDATO: { designacao: "Resetar Prova do Candidato", sigla: "mgea_res" },
  MAPA_ANUAL_ESTUDANTES_FINALISTAS: { designacao: "Mapa Anual de Estudantes Finalistas", sigla: "mgdm_rp" },
  ACESSOS_POR_UTILIZADOR: { designacao: "Acessos Por Utilizador", sigla: "mca_a_laput" },
  LISTA_DOCENTES_REGENTES: { designacao: "Lista De Docentes Regentes", sigla: "mgd_ldr" },
  FAZER_INSCRICAO_GRADE_CURRICULAR: { designacao: "Fazer Inscrição Em Grade Curricular", sigla: "mpgs_a_FIUC" },
  ACESSOS_FUNCIONALIDADES_POR_GRUPO: { designacao: "Acessos/Funcionalidades Por Grupo", sigla: "mca_a_lapg" },
  PAUTA_GERAL_EXAME_ACESSO: { designacao: "Pauta Geral Exame de Acesso", sigla: "mgea_pg" },
  ADMITIR_CANDIDATO: { designacao: "Admitir Candidato", sigla: "mgea_ac" },
  ACTUALIZAR_SENHA_DOCENTE: { designacao: "Actualizar Senha Docente", sigla: "mgu_a_asd" },
  VISUALIZAR_HORARIO_POR_DOCENTE: { designacao: "Visualizar Horário Por Docente", sigla: "mgh_vhpd" },
  LISTAR_SOLICITACOES: { designacao: "Listar Solicitações", sigla: "ls" },
  LISTA_INSCRICOES_POR_HORARIOS: { designacao: "Lista De Inscrições Por Horarios", sigla: "mgh_liph" },
  VISUALIZAR_HORARIO_POR_SALA: { designacao: "Visualizar Horário Por Sala", sigla: "mgh_vhs" },
  REGISTRO_PRIMARIO_MATRICULADOS: { designacao: "Registo Primário de Matriculados", sigla: "mgdm_ta" },
  TALA_EM_DESUSO: { designacao: "Talão Em Desuso", sigla: "maf_tr" },
  MIGRACAO_DADOS_AREA_FINANCEIRA_POS_GRADUACAO: { designacao: "Migração Dados Area Financeira Pós-Graduação", sigla: "mpgs_a_mddos" },
  DEFINIR_ESPECIALIDADE_POS_GRADUACAO: { designacao: "Definir Especialidade Pós Graduação", sigla: "mga_a_defp" },
  CONTROLE_LANCAMENTOS_SUMARIOS: { designacao: "Controle De Lançamentos Sumários", sigla: "msa_cls" },
  MARCACAO_ASSIDUIDADES_AULAS_CAMPO: { designacao: "Marcação de Assiduidades Aulas de Campo", sigla: "msa_maac" },
  LISTA_CANDIDATOS_ADMITIDOS: { designacao: "Lista De Candidatos Admitidos", sigla: "mgea_ca" },
  ESTATISTICA_NOTAS_LANCADAS: { designacao: "Estatística De Notas Lançadas", sigla: "mav_a_raptd" },
  HORARIOS_COM_CONFLITOS: { designacao: "Hórarios Com Conflitos", sigla: "mgh_hc" },
  LISTA_DOCENTES_AFETADOS: { designacao: "Lista De Docentes Afetados", sigla: "mdg_a_ldatd" },
  REGISTRO_PRIMARIO_BD_POS_GRADUACAO: { designacao: "Registo Primário Base de dados Pós-Graduação", sigla: "mgdm_pg" },
  DEFESA: { designacao: "Defesa", sigla: "mgtfc_p_dfsa" },
  PAGAMENTO_TFC: { designacao: "Pagamento Do TFC", sigla: "mgtfc_a_ptfc" },
  ACTIVIDADES_LECTIVAS: { designacao: "Actividades Lectivas", sigla: "mcal_al" },
  HISTORICO_ATUALIZACAO_SALDO: { designacao: "Histórico Actualização De Saldo", sigla: "mga_a_has" },
  PERMISSAO_LANC_NOTA_FORA_PRAZO: { designacao: "Permissão Lanç.Nota Fora do Prazo", sigla: "mva_plnfp" },
  MARCAR_DEFESA: { designacao: "Marcar Defesa", sigla: "mgtfc_a" },
  LISTAR_VIGILANTES_POR_PROVA: { designacao: "Listar Vigilantes Por Prova", sigla: "mav_a_lvpp" },
  DEFINIR_DIRECTOR_CURSO: { designacao: "Definir Director De Curso", sigla: "mca_dr" },
  LISTAR_AFETACOES_POR_UC: { designacao: "Listar Afetações Por UC", sigla: "mgd_lap" },
  CONTROLE_ATUALIZACAO_SALDO: { designacao: "Controle de Atualização de Saldo", sigla: "maf_cs" },
  HORAS_DE_VIGILANCIA: { designacao: "Horas De Vigilancia", sigla: "mgd_hv" },
  MARCAR_ASSIDUIDADE_PROVA: { designacao: "Marcar Assiduidade Prova", sigla: "mav_a_map" },
  LISTAR_ESTUDANTES_POR_ESTADO_MATRICULA: { designacao: "Listar Estudantes Por Estado Da Matricula", sigla: "mgim_a_lepem" },
  LISTAR_ESTUDANTES_FINALISTAS: { designacao: "Listar Estudantes Finalistas", sigla: "mgtfc_m_lef" },
  PERMISSAO_PARA_EDITAR_HORARIO: { designacao: "Permissão Para Editar Horário", sigla: "mgh_a_pedh" },
  ISENCAO_PAGAMENTOS: { designacao: "Isenção De Pagamentos", sigla: "mgtf_a_ip" },
  ESTUDANTES_INSCRITOS_POR_AVALIACAO: { designacao: "Estudantes Inscritos por Avaliação", sigla: "mgim_leir" },
  ACTIVAR_MATRICULA_CANCELADA: { designacao: "Activar Matrícula Cancelada", sigla: "mga_a_amc" },
  PRAZOS_PARA_CRIACAO_HORARIOS: { designacao: "Prazos Para Criação De Horários", sigla: "mcal_a_pch" },
  ACTIVIDADES_LECTIVAS_MPGS: { designacao: "Actividades Lectivas", sigla: "mpgs_a_al" },
  CALENDARIO_PROVAS: { designacao: "Calendârio de Provas", sigla: "mpgs_a_cp" },
  PRAZO_MARCACAO_PROVAS_LANC_NOTAS: { designacao: "Prazo De Marcação De Provas e Lanç. Notas", sigla: "mpgs_a_pmpln" },
  PRAZO_CRIACAO_HORARIOS_MPGS: { designacao: "Prazo Para Criação De Horários", sigla: "mpgs_a_pch" },
  LISTAR_HORARIOS_SEM_COM_SALA: { designacao: "Listar Horários Sem/Com Sala", sigla: "mgh_a_hssd" },
  LISTA_ESTUDANTES_POR_NACIONALIDADE: { designacao: "Lista De Estudantes Por Nacionalidade", sigla: "mgea_lee" },
  IMAGEM_ABERTURA_PORTAL_ESTUDANTE: { designacao: "Imagem De Abertura (Portal Estudante)", sigla: "mc_img" },
  PARAMETROS_GERAIS_AVALIACAO: { designacao: "Parametros Gerais para Avaliação", sigla: "mav_pga" },
  LISTAGEM_GERAL_ESTUDANTES: { designacao: "Listagem Geral De Estudantes", sigla: "mgim_lge" },
  ESTUDANTES_DEVEDORES: { designacao: "Estudantes Devedores", sigla: "mpgs_a_edv" },
  PAUTA_GERAL_POR_UC: { designacao: "Pauta Geral Por Uc", sigla: "mav_lgp" },
  ESTUDANTES_INATIVOS_AC: { designacao: "Estudantes Inativos AC", sigla: "mga_a_eiac" },
  DIAS_MARCADOS_ISENTOS: { designacao: "Dias marcados como Isentos", sigla: "mcal_dmc" },
  HISTORICO_ATUALIZACAO_SALDO_MAF: { designacao: "Histórico da Atualização de Saldo", sigla: "maf_hasa" },
  LISTAR_ESTUDANTES_COM_ISENCAO_PROPINA: { designacao: "Listar Estudantes com Isenção de Propina", sigla: "maf_ei" },
  LANCAMENTO_PROGRAMA_UC: { designacao: "Lancamento do Programa Da Uc", sigla: "mgd_lp" },
  ORIENTANDOS_POR_DOCENTE: { designacao: "Orientandos Por Docente", sigla: "mgtf_a_opd" },
  LISTAR_ESTADO_MATRICULA_ESTUDANTE_POR_HORARIO: { designacao: "Listar Estado Da Matrícula Do Estudante Por Horário", sigla: "mgim_a_lemeh" },
  HISTORICO_BOLSAS: { designacao: "Histórico de Bolsas", sigla: "mgbd_hdb" },
  LISTA_ESTUDANTES_INATIVOS: { designacao: "Lista De Estudantes  Inativos", sigla: "mgtfc_a_lefd" },
  MEUS_ORIENTANDOS: { designacao: "Meus Orientandos", sigla: "mgtfc_p_mo" },
  ORIENTADORES: { designacao: "Orientadores", sigla: "mgtfc_p_o" },
  PARAMETROS_TFC: { designacao: "Parâmetros TFC", sigla: "mgtfc_p_pt" },
  LISTA_ESTUDANTES_FINALISTAS_INACTIVOS: { designacao: "Lista De Estudantes Finalistas Inactivos", sigla: "mgtfc_a_d" },
  DISCIPLINAS_SEM_SIGLA: { designacao: "Disciplinas sem Sigla", sigla: "mpe_csd" },
  LISTA_ESTUDANTES_PERSONALIZADA: { designacao: "Lista de Estudantes Personalizada", sigla: "mca_p_leemi" },
  VALIDACAO_PROGRAMA_UC: { designacao: "Validação do Programa Da Uc", sigla: "mgdv_lp" },
  PARAMETROS_ANO_LECTIVO: { designacao: "Parametros Ano-Lectivo", sigla: "mcal_pal" },
  LISTAR_DOCENTES_SUBSTITUTO: { designacao: "Listar Docentes Substituto", sigla: "mgh_p_lds" },
  HISTORICO_LANCAMENTO_NOTAS: { designacao: "Histórico de lancamento de Notas", sigla: "mav_hln" },
  FUNCIONALIDADES_POR_UTILIZADOR: { designacao: "Funcionalidades por Utilizador", sigla: "mca_a_fpu" },
  CONTROLE_GERAL_SUMARIOS_ASSIDUIDADE: { designacao: "Controle Geral De Sumários e Assiduidade", sigla: "msa_cgs" },
  ADMITIR_CANDIDATURA_UNIVERSIDADE_PUBLICA: { designacao: "Adimitir Candidatura Universidade Pública", sigla: "mgea_a_acup" },
  ALTERAR_PROVA: { designacao: "Alterar Prova", sigla: "mgea_a_ap" },
  LANCAMENTO_NOTAS_MPGS: { designacao: "Lançamento de Notas", sigla: "mpgs_ln" },
  LANCAR_NOTA_CANDIDATURA_ARQUITETURA: { designacao: "Lançar Nota Candidatura Arquitectura e Urbanismo", sigla: "mgea_p_acau" },
  LISTA_ESTUDANTES_MATRICULADOS: { designacao: "Lista De Estudantes Matriculados", sigla: "mpgs_cm" },
  SUMARIOS_POR_LANCAR_LAST52: { designacao: "Sumários Por Lançar last 52", sigla: "msa_spl_bkup" },
  ANULAR_DIPLOMA_ESTUDANTE: { designacao: "Anular Diploma do Estudante", sigla: "mga_a_ddp" },
  LISTA_ESTUDANTES_DIVERSOS_POS_GRAD: { designacao: "Lista De Estudandes", sigla: "mpgs_cmnn" },
  LANCAMENTO_PAUTA: { designacao: "Lancamento da Pauta", sigla: "mgd_lpg" },
  VALIDACAO_PAUTA_DOCENTE: { designacao: "Validação da Pauta Do Docente", sigla: "mgdv_p" },
  ALTERAR_ESTADO_PAGAMENTO: { designacao: "Alterar Estado do Pagamento", sigla: "maf_p" },
  LISTAR_LOGS_ACESSO: { designacao: "Listar Logs de Acesso", sigla: "mca_a_logsi" },
  LISTAGEM_ESTUDANTES_PROPINAS: { designacao: "Listagem De Estudantes Com propinas paga por mês", sigla: "mgim_lep" },
  LISTAR_MENSALIDADES_POR_CURSO: { designacao: "Listar Mensalidades Por Curso", sigla: "mgim_lmc" },
  LISTA_DOCENTE_CONTRATO: { designacao: "Lista de docente com contrato", sigla: "mgd_ldcc" },
  UTILIZADORES_LOGADOS_CHAT: { designacao: "Utilizadores logados (Chat)", sigla: "mca_a_chat" },
  CARGOS_REITORIA_ADMINISTRATIVO: { designacao: "Cargos reitoria e administrativo", sigla: "mca_cr" },
  ESTATISTICA_ESTUDANTES_APROVADOS_REPROVADOS: { designacao: "Estatistica De Estudantes Aprovados e Reprovados", sigla: "mgim_estati" },
  LISTA_CANDIDATOS_SEM_PROVAS_MARCADAS: { designacao: "Lista De Candidatos Sem Provas Marcadas", sigla: "mgea_lcsp" },
  LISTAR_HORARIO_PROVA_POR_CURSO: { designacao: "Listar Horario de Prova por Curso", sigla: "mgea_lhpc" },
  GESTAO_UNIDADE_CURRICULAR_DEPARTAMENTO: { designacao: "Gestão de Unidade Curricular no Departamento", sigla: "mpe_gucd" },
  LISTA_CANDIDATOS_ADMITIDOS_SEM_MATRICULAS: { designacao: "Lista de Candidatos Admitidos Sem Matriculas", sigla: "mgea_lcsm" },
  BLOQUEAR_ACESSOS: { designacao: "Bloquear acessos", sigla: "mca_bloq_acess" },
  CONTROLE_GERAL_ASSIDUIDADE_POR_DOCENTE: { designacao: "Controle Geral de Assiduidade por Docente", sigla: "msa_cgad" },
  MINHAS_ASSIDUIDADES: { designacao: "Minhas Assiduidades", sigla: "msa_mas" },
  MODULOS: { designacao: "Modulos", sigla: "mca_m" },
  ACESSOS_TODOS: { designacao: "Acessos(Todos)", sigla: "mca_a" },
  PAGINAS: { designacao: "Paginas", sigla: "mca_p" },
  CRIAR_HORARIO_POR_TURMA1: { designacao: "Criar Horário Por Turma 1", sigla: "mgh_ch" },
  LISTAR_HORARIOS: { designacao: "Listar Horários", sigla: "mgh_lh" },
  CRIAR_HORARIO: { designacao: "Criar Horário", sigla: "mgh_chuc" },
  CRIAR_TURMA: { designacao: "Criar Turma", sigla: "mgtm_ct" },
  LISTAR_UTILIZADORES_LOGADOS: { designacao: "Listar utilizadores logados", sigla: "mcs_lul" },
  UTILIZADORES: { designacao: "Utilizadores", sigla: "mca_u_i" },
  GRUPOS: { designacao: "Grupos", sigla: "mca_g_i" },
  ATRIBUICAO_BOLSA_DESCONTO: { designacao: "Atribuição de Bolsa e Desconto", sigla: "mgbd_cb" },
  VISUALIZAR_HORARIO_POR_UC: { designacao: "Visualizar Horário Por U.C", sigla: "mgh_vh" },
  HORARIO_AULAS_SEMANAL: { designacao: "Horário De Aulas Semanal", sigla: "mgh_vh_pd" },
  LISTAR_SOLICITACOES_MC: { designacao: "Listar Solicitações", sigla: "mc_ls" },
  SOLICITACOES_ENCAMINHADAS: { designacao: "Solicitações Encaminhadas", sigla: "mc_se" },
  SOLICITACOES_ENCAMINHADAS2: { designacao: "Solicitações Encaminhadas 2", sigla: "mc_se2" },
  INSTITUICOES: { designacao: "Instituições", sigla: "mgbd_ip" },
  ISENCAO_PAGAMENTOS_MGBD: { designacao: "Isenção De Pagamentos", sigla: "mgbd_isp" },
  LISTAR_BOLSEIROS: { designacao: "Listar Bolseiros", sigla: "mgbd_lb" },
  ISENCAO_PAGAMENTOS_MGBD_LS: { designacao: "Isenção De Pagamentos", sigla: "mgbd_ls" },
  PAGAMENTOS_BOLSEIROS: { designacao: "Pagamentos Bolseiros", sigla: "mgbd_pb" },
  PERCENTAGEM_APROVEITAMENTO: { designacao: "Percentagem de Aproveitamento", sigla: "mgbd_tp" },
  AVISOS: { designacao: "Avisos", sigla: "mc_av" },
  MARCAR_ASSIDUIDADE_MSA: { designacao: "Marcar Assiduidade", sigla: "msa_ma" },
  LISTAR_CANDIDATURAS_DOCENTE: { designacao: "Listar Candidaturas de Docente", sigla: "mgd_lc" },
  CALENDARIO_PROVAS_MCAL: { designacao: "Calendário de Provas", sigla: "mcal_ca" },
  LISTA_PRESENCA: { designacao: "Lista De Presença", sigla: "mpgs_lpa" },
  CANDIDATOS_INSCRITOS: { designacao: "Candidatos Inscritos", sigla: "mpgs_ca" },
  ESTATISTICA_MGBD: { designacao: "Estatística", sigla: "mgbd_e" },
  DEFINIR_PRAZOS_ESTADOS_MATRICULA: { designacao: "Definir Prazos e  Estados de Matrícula", sigla: "mcal_dpem" },
  PRAZO_MARCACAO_PROVAS_LANC_NOTAS2: { designacao: "Prazo de Marcação de Provas & Lanç.Notas", sigla: "mcal_dp" },
  DEFINIR_VAGAS_POR_CURSO: { designacao: "Definir Vagas por Curso", sigla: "mcal_dvpcs" },
  DEFINIR_VAGAS_POR_CURSO2: { designacao: "Definir Vagas Por Curso", sigla: "mcal_dvpc" },
  ESTUDANTES_COM_PROPINAS_PAGA: { designacao: "Estudantes Com Propinas Paga", sigla: "mpgs_epg" },
  ESTUDANTES_MATRICULADOS_MPGS: { designacao: "Estudantes Matriculados", sigla: "mpgs_cm" },
  DIAS_ISENTOS: { designacao: "Dias Isentos", sigla: "DI" },
  LANCAMENTO_NOTAS_MPGS2: { designacao: "Lançamento de Notas", sigla: "mpgs_ln" },
  ACTUALIZACAO_DADOS_DOCENTE: { designacao: "Actualização De Dados Docente", sigla: "mgd_add" },
  LISTAR_FACULDADES: { designacao: "Listar Faculdades", sigla: "meoa_lf" },
  ESTUDANTES_POR_UC: { designacao: "Estudantes Por Unidade Curricular", sigla: "mpgs_lepuc" },
  VISUALIZAR_ASSIDUIDADES: { designacao: "Visualizar Assiduidades", sigla: "msa_spl" },
  PARAMETROS_MGH: { designacao: "Parametros", sigla: "mgh_p_i" },
  API_TESTES: { designacao: "Api - Testes", sigla: "mgh_s_a_f" },
  CALENDARIO_AULAS: { designacao: "Calendario De Aulas", sigla: "msa_pd_c_i" },
  LISTAR_INSCRITOS_UC: { designacao: "Listar Inscritos em Unidade Curricular", sigla: "mgim_ic" },
  LISTAR_ESTUDANTES_MATRICULADOS2: { designacao: "Listar Estudantes Matriculados", sigla: "mgim_a_m" },
  SUMARIOS_LANCADOS: { designacao: "Sumarios Lançados", sigla: "msa_sl" },
  GESTAO_AFETACOES: { designacao: "Gestão de Afetações", sigla: "mgd_la" },
  TRABALHO_FIM_CURSO: { designacao: "Trabalho De Fim De Curso", sigla: "mpgs_atfc" },
  SUMARIO_POR_VALIDAR: { designacao: "Sumário Por Validar", sigla: "msa_spv" },
  PARAMETROS_MGD: { designacao: "parametros", sigla: "mgd_p" },
  LISTAR_ESTUDANTES_SEM_INSCRICOES_CURSO: { designacao: "Listar Estudantes Sem Inscrições No Curso", sigla: "mgim_esi" },
  LISTAR_ESTUDANTES_SEM_INSCRICAO_UC: { designacao: "Listar Estudantes Sem Inscrição Em U.C", sigla: "mgim_esic" },
  VALIDACAO_DOCENTE: { designacao: "Validação Docente", sigla: "mgd_ad" },
  PARAMETROS_MSA: { designacao: "Parâmetros", sigla: "msa_p_i" },
} as const;

// Tipo auxiliar para facilitar o uso
export type PermissionDetail = {
  designacao: string;
  sigla: string;
};

// Exemplo de uso:
// const detail = PermissionTypeDetails[PermissionType.FULL_ACCESS];
// console.log(detail.designacao); // "Todos os acesso"